name: Build and Deploy DawahPlay Prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build
        env:
            REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
            REACT_APP_API_ADMINISTER_BASE_URL: ${{ secrets.REACT_APP_API_ADMINISTER_BASE_URL }}
            REACT_APP_DEV_API_BASE_URL: ${{secrets.REACT_APP_DEV_API_BASE_URL}}
            REACT_APP_GOOGLE_PLAY_URL: ${{ secrets.GOOGLE_PLAY_URL }}
            REACT_APP_APPLE_STORE_URL: ${{ secrets.APPLE_STORE_URL}}
            REACT_APP_POSTHOG_KEY: ${{secrets.REACT_APP_POSTHOG_KEY}}
            REACT_APP_POSTHOG_HOST: ${{secrets.REACT_APP_POSTHOG_HOST}}

      - name: Copy static assets into build
        run: |
          mkdir -p build/assets
          cp -R src/assets/* build/assets/ || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync \
            --delete \
            build/ s3://dawahplay-prod

      - name: Invalidate CloudFront cache
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
