name: Build and Deploy DawahPlay Staging

on:
  push:
    branches:
      - staging

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: install Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build React app
      run: bun run build
      env:
            REACT_APP_API_BASE_URL: ${{ secrets.BASE_URL }}
            REACT_APP_API_ADMINISTER_BASE_URL: ${{ secrets.ADMIN_BASE_URL }}
            REACT_APP_GOOGLE_PLAY_URL: ${{ secrets.GOOGLE_PLAY_URL }}
            REACT_APP_APPLE_STORE_URL: ${{ secrets.APPLE_STORE_URL}}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 sync \
          --delete \
          build/ s3://dawahplay-staging

    - name: Invalidate CloudFront cache
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
      run: | 
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
